{
 "title": "Confluent Platform",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_THANOS", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "namespace", "label": "namespace", "query": "confluent" },
   {
    "name": "component_name",
    "label": "Component",
    "query": {
     "query": "label_values(kube_pod_labels{label_confluent_platform=~\"true\",label_platform_confluent_io_type=~\"$controller_type\"}, label_app)"
    }
   },
   {
    "name": "producer_client",
    "label": "producer_client",
    "query": {
     "query": "label_values(kafka_producer_producer_metrics_request_rate,client_id)"
    }
   },
   {
    "name": "consumergroup",
    "label": "consumergroup",
    "query": {
     "query": "label_values(kafka_consumer_group_ConsumerLagMetrics_Value, groupId)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_server_brokertopicmetrics_count, topic)"
    }
   },
   { "name": "job", "query": "kafka" }
  ]
 },
 "panels": [
  { "title": "SchemaLink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Schema Exporter Error Rate by Http Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(schemaregistry_confluent_jersey_metrics_exporters_create_request_error_rate) by (http_status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schema Exporter Error Rate by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "max(schemaregistry_confluent_jersey_metrics_exporters_create_request_error_rate) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schema Exporter Request Latency Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(schemaregistry_confluent_jersey_metrics_exporters_resume_request_latency_max) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schema Exporter Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "sum(schemaregistry_confluent_jersey_metrics_exporters_create_request_error_count) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ClusterLinks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "ClusterLink DeadThreadCount",
   "type": "graph",
   "description": "Byte Rate",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_link_clusterlinkfetchermanager_value{name=\"DeadThreadCount\", job=\"kafka\"}) by (link_name)",
     "legendFormat": "{{ link_name }}"
    }
   ]
  },
  {
   "title": "ClusterLink Lag",
   "type": "graph",
   "description": "Byte Rate",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_link_clusterlinkfetchermanager_value{name=\"TotalLag\", job=\"kafka\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "io_confluent_caas_volumemetrics_used{cluster=\"$cluster\", namespace=~\"confluent\"}",
     "legendFormat": "Used {{ pod }}"
    },
    {
     "expr": "io_confluent_caas_volumemetrics_total{cluster=\"$cluster\", namespace=~\"confluent\"}",
     "legendFormat": "Total {{pod }}"
    }
   ]
  },
  {
   "title": "Disk Usage (Percentage)",
   "type": "graph",
   "description": "Kafka Broker Pods Disk Usage",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "io_confluent_caas_volumemetrics_percentused{namespace=~\"confluent\", cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Disk Availabe (Percentage)",
   "type": "graph",
   "description": "Kafka Broker Pods Disk Usage",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "io_confluent_caas_volumemetrics_percentavailable{cluster=\"$cluster\", namespace=~\"confluent\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU/Mem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"confluent\"}[15m])) by ( pod)"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=\"$cluster\", namespace=~\"confluent\",container=~\"\"}) by (namespace, pod)"
    }
   ]
  },
  {
   "title": "Confluent Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "description": "Number of Brokers Online",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_value{cluster=\"$cluster\", name=\"LeaderCount\",job=\"kafka\",namespace=~\"confluent\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(kafka_controller_kafkacontroller_value{cluster=\"$cluster\", name=\"ActiveControllerCount\",namespace=~\"confluent\",job=\"kafka\"}))"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "stat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_oneminuterate{cluster=\"$cluster\", name=~\"UncleanLeaderElectionsPerSec\",namespace=~\"confluent\",job=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "description": "Partitions that are online",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{cluster=\"$cluster\", name=~\"PartitionCount\",namespace=~\"confluent\",job=~\"kafka\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{cluster=\"$cluster\", name=~\"UnderReplicatedPartitions\",namespace=~\"confluent\",job=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{cluster=\"$cluster\", name=~\"OfflineReplicaCount\",kubernetes_namespace=~\"confluent\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})"
    }
   ]
  },
  {
   "title": "Byte Rate per Topic",
   "type": "timeseries",
   "description": "Byte Rate per Topic",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$cluster\", name=~\"BytesInPerSec\",namespace=~\"confluent\",job=\"kafka\"}) by (topic)",
     "legendFormat": "{{ topic }} "
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$cluster\", name=\"~BytesOutPerSec\",kubernetes_namespace=~\"confluent\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"}) by (topic)",
     "legendFormat": "{{ topic }} "
    }
   ]
  },
  {
   "title": "Messages In Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$cluster\", name=~\"MessagesInPerSec\",namespace=~\"confluent\",job=~\"kafka\"}) by (topic)",
     "legendFormat": "{{Messages In Per Second}}"
    }
   ]
  },
  {
   "title": "Total Broker throughput",
   "type": "graph",
   "description": "Byte Rate",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$cluster\", name=\"BytesInPerSec\",namespace=~\"confluent\",job=\"kafka\"})\n+ sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$cluster\", name=\"ReassignmentBytesInPerSec\",namespace=~\"confluent\",job=\"kafka\"})\n+ sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$cluster\", name=\"ReplicationBytesInPerSec\",namespace=~\"confluent\",job=\"kafka\"})",
     "legendFormat": "Incoming Byte Rate"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$cluster\", name=\"BytesOutPerSec\",kubernetes_namespace=~\"confluent\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"})",
     "legendFormat": "Outgoing Byte Rate"
    }
   ]
  },
  {
   "title": "Produce Request Rate",
   "type": "graph",
   "description": "Produce Request Rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$cluster\", name=\"TotalProduceRequestsPerSec\",namespace=~\"confluent\",job=~\"kafka\"})",
     "legendFormat": "Total Produce Request Rate"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$cluster\", name=\"FailedProduceRequestsPerSec\",namespace=~\"confluent\",job=~\"kafka\"})",
     "legendFormat": "Failed Produce Request Rate"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle Percent",
   "type": "graph",
   "description": "Request Handler Avg Idle Percent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_oneminuterate{cluster=\"$cluster\", name=~\"RequestHandlerAvgIdlePercent\",namespace=~\"confluent\",job=~\"kafka\"}*100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle Percent",
   "type": "graph",
   "description": "Network Processor Avg Idle Percent",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_socketserver_value{name=~\"NetworkProcessorAvgIdlePercent\", cluster=\"$cluster\", namespace=~\"confluent\",job=~\"kafka\"}*100",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Fetch Request Rate",
   "type": "graph",
   "description": "Fetch Request Rate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$cluster\", name=~\"TotalFetchRequestsPerSec\",namespace=~\"confluent\",job=~\"kafka\"})",
     "legendFormat": "Fetch Request Rate"
    },
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$cluster\", name=~\"FailedFetchRequestsPerSec\",namespace=~\"confluent\",job=~\"kafka\"})",
     "legendFormat": "Failed Fetch Request Rate"
    }
   ]
  },
  {
   "title": "Zookeeper Disk Usage (txnlog)",
   "type": "graph",
   "description": "Zookeeper Disk Usage (txnlog)",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"txnlog-$component_name.*\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Confluent ControlCenter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Healthcheck Streams Status",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "confluent_controlcenter_healthcheck_streams_status{kubernetes_namespace=~\"$namespace\",app=~\"$component_name\",platform_confluent_io_type=~\"$controller_type\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}