{
 "title": "MSK Cluster Overview_v1",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_THANOS", "label": "DataSource", "query": "prometheus" },
   {
    "name": "clustername",
    "label": "cluster",
    "query": {
     "query": "label_values(kafka_server_BrokerTopicMetrics_Count, mskcluster)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(kafka_server_BrokerTopicMetrics_Count, region)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_server_BrokerTopicMetrics_Count, topic)"
    }
   },
   {
    "name": "consumergroup",
    "label": "ConsumerGroup",
    "query": {
     "query": "label_values(kafka_consumer_group_ConsumerLagMetrics_Value{topic=~\"$topic\"}, groupId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Critical Values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kafka Broker Count",
   "type": "stat",
   "description": "Kafka Under Replicated Partitions for MSK cluster",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_KafkaServer_Value{name=\"BrokerState\",region=~\"$region\",mskcluster=~\"$clustername\"}) "
    }
   ]
  },
  {
   "title": "In-Sync Replica state change",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_controller_ControllerStats_Count{name=\"IsrChangeRateAndTimeMs\", region=~\"$region\",mskcluster=~\"$clustername\"}[30m]))"
    }
   ]
  },
  {
   "title": "Fetch Queue Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_Fetch_queue_size{region=~\"$region\",mskcluster=~\"$clustername\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Offline Partitions Count",
   "type": "stat",
   "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{name=~\"OfflineReplicaCount\",region=~\"$region\",mskcluster=~\"$clustername\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"OfflinePartitionsCount\",region=~\"$region\",mskcluster=~\"$clustername\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Log Flush Latency (ms)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_log_LogFlushStats_Count{name=\"LogFlushRateAndTimeMs\",region=~\"$region\",mskcluster=~\"$clustername\"}) without (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Partitions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{name=\"GlobalPartitionCount\",region=~\"$region\",mskcluster=~\"$clustername\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{name=~\"UnderReplicatedPartitions\",region=~\"$region\",mskcluster=~\"$clustername\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Number of active controllers in the cluster.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(sum(kafka_controller_KafkaController_Value{name=\"ActiveControllerCount\",region=~\"$region\",mskcluster=~\"$clustername\"}))"
    }
   ]
  },
  {
   "title": "Unclean Leader Election Rate",
   "type": "stat",
   "description": "Unclean leader election rate",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_ControllerStats_OneMinuteRate{name=~\"UncleanLeaderElectionsPerSec\",region=~\"$region\",mskcluster=~\"$clustername\"})"
    }
   ]
  },
  {
   "title": "Preferred Leader Imbalance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{name=\"PreferredReplicaImbalanceCount\",region=~\"$region\",mskcluster=~\"$clustername\"}) without (instance)"
    }
   ]
  },
  {
   "title": "Total Topics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{name=\"GlobalTopicCount\",region=~\"$region\",mskcluster=~\"$clustername\"}) without (instance)\n"
    }
   ]
  },
  {
   "title": "Brokers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MSK CPU in %",
   "type": "graph",
   "description": "MSK CPU in %",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{region=~\"$region\",mskcluster=~\"$clustername\"}[10m])) *100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Kafka Disk Storage",
   "type": "graph",
   "description": "Used Kafka Disk Storage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{region=~\"$region\",mskcluster=~\"$clustername\"} * 100) /            node_filesystem_size_bytes{region=~\"$region\",mskcluster=~\"$clustername\"})\n",
     "legendFormat": "{{mountpoint}}-{{instance}}"
    }
   ]
  },
  {
   "title": "TotalProduceRequestsPerSec ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_FifteenMinuteRate{name=\"TotalProduceRequestsPerSec\",region=~\"$region\",mskcluster=~\"$clustername\"}\n",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Byte Rate per Topic",
   "type": "graph",
   "description": "Byte Rate per Topic",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=~\"BytesInPerSec\",region=~\"$region\",topic=~\"$topic\",mskcluster=~\"$clustername\"}) by (topic)",
     "legendFormat": "{{ topic }}"
    }
   ]
  },
  {
   "title": "Broker BytesInPerSec",
   "type": "graph",
   "description": "Broker BytesInPerSec",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=~\"BytesInPerSec\",region=~\"$region\",mskcluster=~\"$clustername\"})\n+ sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=~\"ReassignmentBytesInPerSec\",region=~\"$region\",mskcluster=~\"$clustername\"})\n+ sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=~\"ReplicationBytesInPerSec\",region=~\"$region\",mskcluster=~\"$clustername\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ReplicationBytesInPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"ReplicationBytesInPerSec\",region=~\"$region\",mskcluster=~\"$clustername\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MessagesInPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"MessagesInPerSec\",region=~\"$region\",mskcluster=~\"$clustername\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ReplicationBytesOutPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"ReplicationBytesInPerSec\",region=~\"$region\",mskcluster=~\"$clustername\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under replicated partitions by Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_cluster_Partition_Value{name=\"UnderReplicated\",region=~\"$region\",mskcluster=~\"$clustername\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\"}[1m])) by (name)",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\"}[1m])) by (name)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network: RequestsPerSec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_RequestMetrics_OneMinuteRate{name=\"RequestsPerSec\",region=~\"$region\",mskcluster=~\"$clustername\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network: CPU Idle Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_Processor_Value{name=\"IdlePercent\",region=~\"$region\",mskcluster=~\"$clustername\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network: ErrorsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_RequestMetrics_OneMinuteRate{name=\"ErrorsPerSec\",region=~\"$region\",mskcluster=~\"$clustername\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}