{
 "title": "Confluent Kafka Minion v4",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_THANOS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kminion_kafka_broker_info,k8scluster)"
    }
   },
   {
    "name": "consumer_group",
    "label": "Consumer Group",
    "query": {
     "query": "label_values(kminion_kafka_consumer_group_topic_offset_sum{k8scluster=\"$cluster\"}, group_id)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kminion_kafka_consumer_group_topic_offset_sum{group_id=\"$consumer_group\"}, topic_name)"
    }
   },
   { "name": "kubernetes_pod_name", "label": "kubernetes_pod_name", "query": { "query": "kubernetes_pod_name" } }
  ]
 },
 "panels": [
  {
   "title": "Topic metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Partition Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kminion_kafka_consumer_group_topic_assigned_partitions{k8scluster=\"$cluster\",topic_name=\"$topic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Groups consuming $topic",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "avg by (group_id, topic_name) (kminion_kafka_consumer_group_topic_lag{topic_name=\"$topic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kminion_kafka_consumer_group_topic_lag{group_id=\"$consumer_group\", topic_name=\"$topic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumergroup => Topic Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (group_id,topic_name) (kminion_kafka_consumer_group_topic_lag{group_id=\"$consumer_group\", topic_name=\"$topic\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages In vs Consumed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "avg by (topic_name) (sum by (topic_name, kubernetes_pod_name) (rate(kminion_kafka_consumer_group_topic_offset_sum{group_id=\"$consumer_group\", topic_name=\"$topic\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (topic_name) (sum by (topic_name, kubernetes_pod_name) (rate(kminion_kafka_topic_partition_high_water_mark{topic_name=\"$topic\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Group metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Lag per Partition: $consumer_group => $topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "avg by (group_id,topic_name,partition) (kminion_kafka_consumer_group_topic_partition_lag{group_id=\"$consumer_group\", topic_name=\"$topic\"})",
     "legendFormat": "Partiton {{partition}}"
    }
   ]
  },
  {
   "title": "Lag per Partition: $consumer_group => $topic",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (group_id,topic_name,partition) (kminion_kafka_consumer_group_topic_partition_lag{group_id=\"$consumer_group\", topic_name=\"$topic\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}