{
 "title": "Platform Grafana Metrics",
 "description": "Metrics about Grafana",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_THANOS", "label": "DataSource", "query": "prometheus" },
   {
    "name": "awsaccount",
    "label": "awsaccount",
    "query": {
     "query": "label_values(grafana_build_info, awsaccount)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(grafana_build_info, region)"
    }
   },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster)" } },
   { "name": "pod", "label": "pod", "query": { "query": "label_values(pod)" } },
   {
    "name": "handler",
    "label": "handler",
    "query": {
     "query": "label_values(grafana_http_request_duration_seconds_bucket, handler)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{job=~\".*grafana.*\", awsaccount=\"$awsaccount\", cluster=\"$cluster\", region=\"$region\"})"
    }
   ]
  },
  {
   "title": "Dashboard count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_totals_dashboard{awsaccount=\"$awsaccount\", cluster=~\"$cluster\", region=~\"$region\"})"
    }
   ]
  },
  {
   "title": "User count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_total_users{awsaccount=~\"$awsaccount\", cluster=~\"$cluster\", region=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Playlist count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(grafana_stat_total_playlists{awsaccount=~\"$awsaccount\", cluster=~\"$cluster\", region=~\"$region\"})"
    }
   ]
  },
  {
   "title": "Grafana version",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "topk(1, grafana_info or grafana_build_info)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "http status codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(code) (irate(grafana_api_response_status_total{job=~\".*grafana.*\", awsaccount=~\"$awsaccount\", cluster=~\"$cluster\", region=~\"$region\"}[10m]))",
     "legendFormat": "{{statuscode}}",
     "target": "dev.grafana.cb-office.alerting.active_alerts"
    }
   ]
  },
  {
   "title": "Requests by routing group",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(grafana_api_response_status_total{awsaccount=~\"$awsaccount\", cluster=~\"$cluster\", region=~\"$region\"}[5m]))",
     "legendFormat": "api"
    },
    {
     "expr": "sum(irate(grafana_proxy_response_status_total[5m]))",
     "legendFormat": "proxy"
    },
    {
     "expr": "sum(irate(grafana_page_response_status_total[5m]))",
     "legendFormat": "web"
    }
   ]
  },
  {
   "title": "Most used datasource",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 5 },
   "targets": [
    {
     "expr": "sort(topk(8, sum by (datasource) (grafana_datasource_request_total{job=~\".*grafana.*\"})))",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Grafana active alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(grafana_alerting_active_alerts{awsaccount=~\"$awsaccount\", cluster=~\"$cluster\", region=~\"$region\"}[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": " Grafana Request Latency Percentiles",
   "type": "graph",
   "description": "Total time for NGINX and upstream servers to process a request and send a response",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grafana_http_request_duration_seconds_bucket{handler=~\"$handler\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\"}[10m])))",
     "legendFormat": ".95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(grafana_http_request_duration_seconds_bucket{handler=\"$handler\", awsaccount=\"$awsaccount\", region=\"$region\", cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(grafana_http_request_duration_seconds_bucket{handler=\"$handler\", awsaccount=\"$awsaccount\", region=\"$region\", cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{pod=~\"$pod\", awsaccount=~\"$awsaccount\", cluster=~\"$cluster\", region=~\"$region\"}[5m]))",
     "legendFormat": "CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_resident_memory_bytes{pod=~\"$pod\", awsaccount=~\"$awsaccount\", cluster=~\"$cluster\", region=~\"$region\"}[10m]))",
     "legendFormat": "Resident Mem"
    },
    {
     "expr": "avg(rate(process_virtual_memory_bytes{pod=\"$pod\"}[5m]))",
     "legendFormat": "Virtual Mem"
    }
   ]
  },
  {
   "title": "Grafana performance",
   "type": "timeseries",
   "description": "Aggregated over all Grafana nodes.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=~\".*grafana.*\", awsaccount=\"$awsaccount\", cluster=\"$cluster\", region=\"$region\"})",
     "legendFormat": "go routines",
     "target": "select metric",
     "type": "timeserie"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=\"grafana-service\"})",
     "legendFormat": "memory usage"
    }
   ]
  }
 ]
}