{
 "title": "AWS Lambda",
 "description": "Visualize AWS Lambda metrics",
 "tags": [
  "Amazon",
  "AWS",
  "CloudWatch",
  "Lambda"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" }
  ]
 },
 "panels": [
  { "title": "Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SLA of service",
   "type": "gauge",
   "description": "calculated based on the aggregation of successRate,  expected response time, expected traffic, increased throttle divided by 4.",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "(successRate_sla + response_sla + throttle_sla + invocations_sla) / 4",
     "id": "lambda_sla",
     "label": "Overall SLA",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 1 },
   "options": {
    "content": "<div\nstyle=\"text-align: center\">\n<h1>Traffic<h1>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 1 },
   "options": {
    "content": "<div\nstyle=\"text-align: center\">\n<h1> Latency Stats</h1>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 1 },
   "options": {
    "content": "<div\nstyle=\"text-align: center\">\n<h1>Error Stats<h1>\n</div>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
   "options": {
    "content": "<div\nstyle=\"text-align: center\">\n<h1> Saturation Stats </h1>\n</div>"
   }
  },
  {
   "title": "Traffic",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "100 - invocationsDecrease",
     "id": "invocations_sla",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "100 - actualResponseIncrease",
     "id": "response_sla",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "((executions - errors) / executions) * 100",
     "id": "successRate_sla",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "100 - throttleIncreasePercentage",
     "id": "throttle_sla",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Traffic sum",
   "type": "stat",
   "description": "Expected traffic: xx",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "traffic drop %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "100 - invocationsPercent",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "response time",
   "type": "stat",
   "description": "Expected response: 300ms",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Latency Increase %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "((latency - 300) / 300 ) * 100",
     "id": "latency_Increase_percentage",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "errors sum",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "errors increase %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "100 - errorPercentage",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "throttle sum",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "throttle increase %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "(((1 - throttle) - 1)/1)*100",
     "metricEditorMode": 1,
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "High Level Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Functions by Invocations",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "expression": "SELECT SUM(Invocations) FROM SCHEMA(\"AWS/Lambda\", FunctionName) GROUP BY FunctionName ORDER BY MAX() DESC LIMIT 10",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Top 10 Functions by Duration",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expression": "SELECT AVG(Duration) FROM SCHEMA(\"AWS/Lambda\", FunctionName) GROUP BY FunctionName ORDER BY AVG() DESC LIMIT 10",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Top 10 Functions by Errors",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "expression": "SELECT SUM(Errors) FROM SCHEMA(\"AWS/Lambda\", FunctionName) GROUP BY FunctionName ORDER BY MAX() DESC LIMIT 10",
       "metricEditorMode": 1,
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Total invocations [count/sec]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dimensions": { "FunctionName": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda} MetricName=\"Invocations\"', 'Sum', $period))/$period",
       "metricEditorMode": 1,
       "metricName": "Invocations",
       "namespace": "AWS/Lambda",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Total error rate [errors/invocations]",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "(errors / invocations)",
       "metricEditorMode": 1,
       "metricName": "Invocations",
       "namespace": "AWS/Lambda",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Total error rate [errors/invocations] %",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "(errors / invocations)*100",
       "metricEditorMode": 1,
       "metricName": "Invocations",
       "namespace": "AWS/Lambda",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Total throttle rate [throttles/invocations]",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "throttles / invocations",
       "metricEditorMode": 1,
       "metricName": "Invocations",
       "namespace": "AWS/Lambda",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Total throttle rate [throttles/invocations] %",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "(throttles / invocations)*100",
       "metricEditorMode": 1,
       "metricName": "Invocations",
       "namespace": "AWS/Lambda",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Per function details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Duration per function [average time]  Log scale",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "FunctionName": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda,FunctionName} MetricName=\"Duration\"', 'Average', $period))",
       "metricEditorMode": 1,
       "metricName": "Invocations",
       "namespace": "AWS/Lambda",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Invocations per function [count/sec]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dimensions": { "FunctionName": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda,FunctionName} MetricName=\"Invocations\"', 'Sum', $period))/$period",
       "metricEditorMode": 1,
       "metricName": "Invocations",
       "namespace": "AWS/Lambda",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Errors per function [count/sec]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dimensions": { "FunctionName": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda,FunctionName} MetricName=\"Errors\"', 'Sum', $period))/$period",
       "metricEditorMode": 1,
       "metricName": "Invocations",
       "namespace": "AWS/Lambda",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Throttles per function [count/sec]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dimensions": { "FunctionName": "*" },
       "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda,FunctionName} MetricName=\"Throttles\"', 'Sum', $period))/$period",
       "metricEditorMode": 1,
       "metricName": "Invocations",
       "namespace": "AWS/Lambda",
       "period": "$period",
       "queryMode": "Metrics",
       "region": "$region",
       "statistic": "Sum"
      }
     ]
    }
   ]
  },
  {
   "title": "Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": " Documentation",
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
     "options": {
      "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/lambda/latest/dg/monitoring-functions-metrics.html\">AWS CloudWatch Lambda monitoring documentation</a> | \n<a target=\"_blank\" href=\"https://docs.example.com/document/d/YOUR_DOC_ID/edit#heading=h.n4gub5ficsj2\">EXAMPLE Wiki documentation for compplete list of metrics</a>\n"
     },
     "targets": [
      { "region": "default", "statistic": "Average" }
     ]
    }
   ]
  }
 ]
}