{
 "title": "AWS Network ELB",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Service Level Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Main Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Healthy Host Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "metricName": "HealthyHostCount",
       "namespace": "AWS/NetworkELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "UnHealthy Host Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "metricName": "UnHealthyHostCount",
       "namespace": "AWS/NetworkELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Processed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "dimensions": { "LoadBalancer": "*" },
       "metricName": "ProcessedBytes",
       "namespace": "AWS/NetworkELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Flow Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "dimensions": { "LoadBalancer": "*" },
       "metricName": "ActiveFlowCount",
       "namespace": "AWS/NetworkELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Consumed LCUs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "dimensions": { "LoadBalancer": "*" },
       "metricName": "ConsumedLCUs",
       "namespace": "AWS/NetworkELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "New Flow Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "dimensions": { "LoadBalancer": "*" },
       "metricName": "NewFlowCount",
       "namespace": "AWS/NetworkELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "TLS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Flow Count TLS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "dimensions": { "LoadBalancer": "*" },
       "metricName": "ActiveFlowCount_TLS",
       "namespace": "AWS/NetworkELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Client TLS Negotiation Error Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "dimensions": { "LoadBalancer": "*" },
       "metricName": "ClientTLSNegotiationErrorCount",
       "namespace": "AWS/NetworkELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Processed Bytes TLS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "dimensions": { "LoadBalancer": "*" },
       "metricName": "ProcessedBytes_TLS",
       "namespace": "AWS/NetworkELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Target TLS Negotiation ErrorCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "dimensions": { "LoadBalancer": "*" },
       "metricName": "TargetTLSNegotiationErrorCount",
       "namespace": "AWS/NetworkELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "TCP Client Reset Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "metricName": "TCP_Client_Reset_Count",
     "namespace": "AWS/NetworkELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "TCP ELB Reset Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "metricName": "TCP_ELB_Reset_Count",
     "namespace": "AWS/NetworkELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "TCP Target Reset Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "*" },
     "metricName": "TCP_Target_Reset_Count",
     "namespace": "AWS/NetworkELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Documentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a>\n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-cloudwatch-metrics.html\">AWS CloudWatch NLB documentation</a> | \n<a target=\"_blank\" href=\"https://docs.example.com/document/d/YOUR_DOC_ID/edit#heading=h.n4gub5ficsj2\">EXAMPLE Wiki documentation for complete list of metrics</a>"
   },
   "targets": [
    {}
   ]
  }
 ]
}