{
 "title": "AWS Transit Gateway",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BytesIn / BytesOut",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "TransitGateway": "*" },
     "metricName": "BytesIn",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "TransitGateway": "*" },
     "metricName": "BytesOut",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "PacketsIn / PacketsOut",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "dimensions": { "TransitGateway": "*" },
     "metricName": "PacketsIn",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "TransitGateway": "*" },
     "metricName": "PacketsOut",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "PacketDropCountNoRoute / PacketDropCountBlackhole",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dimensions": { "TransitGateway": "*" },
     "metricName": "PacketDropCountBlackhole",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "TransitGateway": "*" },
     "metricName": "PacketDropCountNoRoute",
     "namespace": "AWS/TransitGateway",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Per TransitAttachment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "BytesIn / BytesOut  for TransitGatewayAttachment",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "dimensions": {
        "TransitGatewayAttachment": "*"
       },
       "metricName": "BytesIn",
       "namespace": "AWS/TransitGateway",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "dimensions": {
        "TransitGatewayAttachment": "*"
       },
       "metricName": "BytesOut",
       "namespace": "AWS/TransitGateway",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "PacketsIn / PacketsOut for TransitGatewayAttachment",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "dimensions": {
        "TransitGatewayAttachment": "*"
       },
       "metricName": "PacketsIn",
       "namespace": "AWS/TransitGateway",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      },
      {
       "dimensions": {
        "TransitGatewayAttachment": "*"
       },
       "metricName": "PacketsOut",
       "namespace": "AWS/TransitGateway",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "PacketDropCountNoRoute / PacketDropCountBlackhole for TransitGatewayAttachment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "dimensions": {
        "TransitGatewayAttachment": "*"
       },
       "metricName": "PacketDropCountBlackhole",
       "namespace": "AWS/TransitGateway",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    }
   ]
  },
  {
   "title": "Documetation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true
  }
 ]
}