{
 "title": "K8s apps",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "namespace", "query": { "query": "kube_namespace_created" } },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "kube_namespace_created{cluster=~\"$cluster\"}"
    }
   },
   {
    "name": "deployment",
    "label": "deployment",
    "query": {
     "query": "kube_deployment_created{exported_namespace =~\"$namespace\"}"
    }
   },
   {
    "name": "ingress",
    "query": {
     "query": "nginx_ingress_controller_requests"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "# of Pods / # of Restarts",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(count(container_memory_usage_bytes{pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=\"$namespace\"}) by (kubernetes_io_hostname))",
       "legendFormat": "# Nodes"
      }
     ]
    },
    {
     "title": "CPU Usage/ limit / Request",
     "type": "bargauge",
     "description": "Datasource: Thanos\n\nInput: namespace, pod\n\nDescription: Increase in CPU will show direct impact on application availability. Check if the app capacity is in right scale. If there is no HPA setup, make sure if the deployment is properly scaled.",
     "gridPos": { "h": 5, "w": 7, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\" ,namespace=~\"^$namespace$\",pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"}[3m]))",
       "legendFormat": "CPU Usage - Average per Pod"
      },
      {
       "expr": "max(kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$namespace$\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"}) ",
       "legendFormat": " Request"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_cpu_cores{namespace=~\"^$namespace$\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory Usage/ limit / Request",
     "type": "bargauge",
     "description": "Datasource: Thanos\n\nInput: namespace, pod\n\nDescription: Increase in Memory will show direct impact on application availability. Check if the app is allocated with enough resources. If there is no HPA setup, make sure if the deployment is properly scaled.",
     "gridPos": { "h": 5, "w": 7, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(sum(container_memory_usage_bytes{container!=\"\", container!=\"POD\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=\"$namespace\"}) by (id,pod) - sum(container_memory_cache{container!=\"\", container!=\"POD\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=\"$namespace\"}) by (id,pod))",
       "legendFormat": "Memory Usage - Average Per Pod"
      },
      {
       "expr": "max(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod_name=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"}) ",
       "legendFormat": " Request"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod_name=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Total Network Pressure",
     "type": "stat",
     "description": "Datasource: Thanos\n\nThresholds: Green: < 500 MBps; Yellow: > 500 MBps; Red: > 1000 MBps\n\nInput: pod, namespace\n\nDescription: Drop in ether In or Out indicated the app is in healthy, check if the app is able to communicate to subsequent services.",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{name=~\"^k8s_.*\",pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=~\"$namespace\"}[3m]))",
       "legendFormat": "In"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{name=~\"^k8s_.*\",pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=~\"$namespace\"}[3m]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "# of pods / # of Restarts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (kube_pod_info{namespace=~\"$namespace\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"})",
       "legendFormat": "# Nodes"
      },
      {
       "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod_name=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"}[15m])) by (pod_name)",
       "legendFormat": "restart: {{pod_name}}"
      }
     ]
    },
    {
     "title": "CPU Usage/ limit/ Request ",
     "type": "graph",
     "description": "Datasource: Thanos\n\nInput: namespace, pod\n\nDescription: Increase in CPU will show direct impact on application availability. Check if the app capacity is in right scale. If there is no HPA setup, make sure if the deployment is properly scaled.",
     "gridPos": { "h": 7, "w": 7, "x": 5, "y": 6 },
     "yaxes": [
      { "format": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",name=~\"^k8s_.*\",namespace=~\"^$namespace$\",pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"}[3m])) by (pod, container)",
       "legendFormat": "Actual: {{container}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_cpu_cores{namespace=~\"^$namespace$\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "max(kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$namespace$\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"})",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "Memory Usage/ limit/ Request ",
     "type": "graph",
     "description": "Datasource: Thanos\n\nInput: namespace, pod\n\nDescription: Increase in Memory will show direct impact on application availability. Check if the app is allocated with enough resources. If there is no HPA setup, make sure if the deployment is properly scaled.",
     "gridPos": { "h": 7, "w": 7, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{container!=\"\", container!=\"POD\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=\"$namespace\"}) by (id,pod) - sum(container_memory_cache{container!=\"\", container!=\"POD\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=\"$namespace\"}) by (id,pod)",
       "legendFormat": "Actual:  {{pod}}"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"})",
       "legendFormat": "Limit"
      },
      {
       "expr": "max(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"})",
       "legendFormat": "Request"
      }
     ]
    },
    {
     "title": "Network",
     "type": "graph",
     "description": "Datasource: Thanos\n\nThresholds: Green: < 500 MBps; Yellow: > 500 MBps; Red: > 1000 MBps\n\nInput: pod, namespace\n\nDescription: Drop in ether In or Out indicated the app is in healthy, check if the app is able to communicate to subsequent services.",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 6 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=\"$namespace\",pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"}[3m])) by (pod)",
       "legendFormat": "In - {{pod}}"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=\"$namespace\",pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"}[3m])) by (pod)",
       "legendFormat": "Out - {{pod}}"
      },
      { "expr": "0", "legendFormat": "Zero" }
     ]
    }
   ]
  },
  {
   "title": "Istio Mesh",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "RPS",
     "type": "gauge",
     "description": "Datasource: Thanos\n\nInputs: istio_service\n\nDescription: Decrease in RPS means the traffic is not hitting istio service. Either the upstream layer is effected or the istio deployment is failing.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{destination_workload=\"kyuubi\",destination_workload_namespace=\"kyuubi\"}[1m]))by(destination_workload_namespace), 0.001)"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "gauge",
     "description": "Datasource: Thanos\n\nInputs: istio_service\n\nDescription: Increase in errors means the response received by downstream layers are not 2xx or the istio deployment is failing.",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(istio_requests_total{destination_workload=\"kyuubi\", response_code=~\"5.*\",destination_workload_namespace=\"kyuubi\"}[1m]))by(destination_workload_namespace) / sum(rate(istio_requests_total{destination_workload=\"kyuubi\",destination_workload_namespace=\"kyuubi\"}[1m]))by(destination_workload_namespace)"
      }
     ]
    },
    {
     "title": "Request Duration ",
     "type": "gauge",
     "description": "Datasource: Thanos\n\nInputs: istio_service\n\nDescription: Increase in request duration means either the downstream layers are responding low or the istio deployment is unhealthy.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_workload=\"kyuubi\",destination_workload_namespace=\"kyuubi\"}[3m]))by(destination_workload_namespace)/sum(rate(istio_request_duration_milliseconds_count{destination_workload=\"kyuubi\",destination_workload_namespace=\"kyuubi\"}[3m]))by(destination_workload_namespace)"
      }
     ]
    },
    {
     "title": "P95 Latency",
     "type": "gauge",
     "description": "Datasource: Thanos\n\nInputs: istio_service\n\nDescription: if 95 percentile of the traffic is showing high in number then the impact could much wider check if downstream layers are responding low or the istio deployment is unhealthy.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "label_join((histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", namespace=\"kyuubi\"}[3m])) by (le, destination_workload, destination_workload_namespace,namespace)) / 1000) or histogram_quantile(0.95, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\", namespace=\"kyuubi\"}[3m])) by (le, destination_workload, destination_workload_namespace,namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
       "legendFormat": "{{destination_workload}}"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "graph",
     "description": "Datasource: Thanos\n\nInputs: istio_service\n\nDescription: Decrease in RPS means the traffic is not hitting istio service. Either the upstream layer is effected or the istio deployment is failing.",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{destination_workload=\"kyuubi\",destination_workload_namespace=\"kyuubi\"}[1m]))by(destination_workload,destination_workload_namespace), 0.001)",
       "legendFormat": "Workload: {{destination_workload}}"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "graph",
     "description": "Datasource: Thanos\n\nInputs: istio_service\n\nDescription: Increase in errors means the response received by downstream layers are not 2xx or the istio deployment is failing.",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(istio_requests_total{destination_workload=\"kyuubi\",destination_workload_namespace=\"kyuubi\",response_code=~\"5.*|4.*\"}[1m]))by(destination_workload,destination_workload_namespace) / sum(rate(istio_requests_total{destination_workload=\"kyuubi\",destination_workload_namespace=\"kyuubi\",response_code=~\"5.*|4.*\"}[1m]))by(destination_workload,destination_workload_namespace)",
       "legendFormat": "{{destination_workload}}_{{response_code}}"
      }
     ]
    },
    {
     "title": "Request Duration ",
     "type": "graph",
     "description": "Datasource: Thanos\n\nInputs: istio_service\n\nDescription: Increase in request duration means either the downstream layers are responding low or the istio deployment is unhealthy.",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(istio_request_duration_milliseconds_count{destination_workload=\"kyuubi\",destination_workload_namespace=\"kyuubi\"}[3m]))by(destination_workload)/sum(rate(istio_request_duration_milliseconds_count{destination_workload=\"kyuubi\",destination_workload_namespace=\"kyuubi\"}[3m]))by(destination_workload)",
       "legendFormat": "app: {{destination_workload}}"
      }
     ]
    },
    {
     "title": "P95 Latency",
     "type": "graph",
     "description": "Datasource: Thanos\n\nInputs: istio_service\n\nDescription: if 95 percentile of the traffic is showing high in number then the impact could much wider check if downstream layers are responding low or the istio deployment is unhealthy.",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", namespace=\"kyuubi\"}[3m])) by (le, destination_workload, destination_workload_namespace,namespace))",
       "legendFormat": "app: {{destination_workload}}"
      }
     ]
    },
    {
     "title": "HTTP/GRPC Workloads",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "label_join(sum(rate(istio_requests_total{response_code=\"200\",destination_workload=\"productconfigapi-argon\",destination_workload_namespace=\"argon\"}[1m])) by (destination_workload, destination_workload_namespace, destination_service), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
       "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "label_join((histogram_quantile(0.50, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\",namespace=\"istio-system\"}[1m])) by (le, destination_workload, destination_workload_namespace,namespace)) / 1000) or histogram_quantile(0.50, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\", namespace=\"istio-system\"}[1m])) by (le, destination_workload, destination_workload_namespace,namespace,)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
       "legendFormat": "{{ destination_workload}}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "label_join((histogram_quantile(0.90, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", namespace=\"istio-system\"}[1m])) by (le, destination_workload, destination_workload_namespace,namespace)) / 1000) or histogram_quantile(0.90, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\", namespace=\"istio-system\"}[1m])) by (le, destination_workload, destination_workload_namespace,namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "label_join((histogram_quantile(0.99, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\", namespace=\"istio-system\"}[1m])) by (le, destination_workload, destination_workload_namespace,namespace)) / 1000) or histogram_quantile(0.99, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\", namespace=\"istio-system\"}[1m])) by (le, destination_workload, destination_workload_namespace,namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      },
      {
       "expr": "label_join((sum(rate(istio_requests_total{reporter=\"destination\", response_code!~\"5.*\", namespace=\"istio-system\"}[1m])) by (destination_workload, destination_workload_namespace,namespace) / sum(rate(istio_requests_total{reporter=\"destination\", namespace=\"istio-system\"}[1m])) by (destination_workload, destination_workload_namespace,namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
       "legendFormat": "{{ destination_workload }}.{{ destination_workload_namespace }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "RPS",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(sum(rate(nginx_ingress_controller_requests{ingress=~\"^$ingress$\", namespace=\"$namespace\"}[5m])) by (ingress))"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(sum(rate(nginx_ingress_controller_requests{status=~\"[4-5].*\",ingress=~\"^$ingress$\", namespace=\"$namespace\"}[5m])) by (ingress))"
      }
     ]
    },
    {
     "title": "Request Duration ",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{namespace=\"$namespace\",ingress=~\"$ingress\"}[3m]))/sum(rate(nginx_ingress_controller_request_duration_seconds_count{namespace=\"$namespace\",ingress=~\"$ingress\"}[3m]))"
      }
     ]
    },
    {
     "title": "P95 Latency",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95,sum by (le)(rate(nginx_ingress_controller_response_duration_seconds_bucket{namespace=\"$namespace\", ingress=~\"$ingress\"}[3m])))"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{ingress=~\"$ingress\", namespace=\"$namespace\"}[5m])) by (ingress)",
       "legendFormat": "{{ingress}}"
      }
     ]
    },
    {
     "title": "Error Rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"[4-5].*\",ingress=~\"$ingress\", namespace=\"$namespace\"}[5m])) by (ingress, status)",
       "legendFormat": "{{ingress}}__{{status}}"
      }
     ]
    },
    {
     "title": "Request Duration ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_sum{namespace=\"$namespace\",ingress=~\"$ingress\"}[3m]))by (ingress, path)/sum(rate(nginx_ingress_controller_request_duration_seconds_count{namespace=\"$namespace\",ingress=~\"$ingress\"}[3m]))by (ingress, path)",
       "legendFormat": "{{ingress}}_{{path}}"
      }
     ]
    },
    {
     "title": "P95 Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 35 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95,sum by (le, ingress, path)(rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress =~ \"$ingress\"}[3m])))",
       "legendFormat": "{{ingress}}__{{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "NLB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Active Flow Count (Avg)",
     "type": "graph",
     "description": "Currently the Platform applications are not using aws NLB but in case if that component is used in future, this panel will show data with no additional effort.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(aws_networkelb_active_flow_count_average{application=\"k8s\"})by(accountname,load_balancer)",
       "legendFormat": "{{accountname}} : {{load_balancer}}"
      }
     ]
    },
    {
     "title": "Healthy Host Count",
     "type": "graph",
     "description": "Currently the Platform applications are not using aws NLB but in case if that component is used in future, this panel will show data with no additional effort.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_networkelb_healthy_host_count_average{application=\"k8s\"})by(load_balancer)",
       "legendFormat": "{{load_balancer}}"
      }
     ]
    },
    {
     "title": "New Flow Count (sum)",
     "type": "graph",
     "description": "Currently the Platform applications are not using aws NLB but in case if that component is used in future, this panel will show data with no additional effort.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_networkelb_new_flow_count_sum{application=~\"k8s\"})by(load_balancer)",
       "legendFormat": "{{load_balancer}}"
      }
     ]
    },
    {
     "title": "Un-Healthy Host Count",
     "type": "graph",
     "description": "Currently the Platform applications are not using aws NLB but in case if that component is used in future, this panel will show data with no additional effort.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(aws_networkelb_un_healthy_host_count_average{application=\"k8s\"})by(load_balancer)",
       "legendFormat": "{{load_balancer}}"
      }
     ]
    }
   ]
  }
 ]
}