{
 "title": "NFR Test Execution Results",
 "time": { "from": "2023-07-01T04:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "kube_namespace_created" } },
   { "name": "namespace", "query": { "query": "kube_namespace_created" } },
   {
    "name": "deployment",
    "query": {
     "query": "kube_deployment_created{exported_namespace=~\"$namespace\"}"
    }
   },
   {
    "name": "container_name",
    "query": {
     "query": "http_server_requests_seconds_count"
    }
   },
   { "name": "istio_service", "label": "Istio Endpoint", "query": { "query": "istio_requests_total" } },
   { "name": "trackingNumber" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 9, "x": 0, "y": 1 },
     "options": {
      "content": "<h1 style=\"text-align: center; color:#3880eb; font-size: 35px\">GRPC metrics</h1>\n"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 14, "x": 10, "y": 1 },
     "options": {
      "content": "<h1 style=\"text-align: center; color:#3880eb; font-size: 35px\">Istio metrics</h1>\n"
     }
    },
    {
     "title": "Worker Threads",
     "type": "stat",
     "description": "Data source: Thanos\n\nquery: thread_pool_thread_count\n\nDescription: A “worker thread” is just a thread which runs to perform some background work, it's configured at code level.",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(thread_pool_thread_count{cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Count",
     "type": "stat",
     "description": "DataSource: Thanos\n\nQuery: thread_pool_queue_size\n\nDescription: A connection is active when it is used by a thread of the application, which means, the connection is outside the pool and cannot be used by any other thread. If Active count == Thread pool then all the resources are being used, which may lead to exhaustiveness.",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(thread_pool_active_size{cluster=~\"$cluster\",container_name=~\"$container_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pending Requests",
     "type": "stat",
     "description": "DataSource: Thanos\n\nQuery: thread_pool_queue_size\n\nDescription: A pending thread is a thread that requires a connection but couldn’t find any inside the pool, more pending request implies the system is exhausted with threads.",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(thread_pool_queue_size{cluster=~\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "label_join((histogram_quantile(0.95, sum(rate(istio_request_duration_milliseconds_bucket{reporter=\"destination\"}[3m])) by (le, destination_workload, destination_workload_namespace)) / 1000) or histogram_quantile(0.95, sum(rate(istio_request_duration_seconds_bucket{reporter=\"destination\"}[3m])) by (le, destination_workload, destination_workload_namespace)), \"destination_workload_var\", \".\", \"destination_workload\", \"destination_workload_namespace\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bandwidth",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 15, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{name=~\"^k8s_.*\",pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=~\"$namespace\"}[3m]))",
       "legendFormat": "In"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{name=~\"^k8s_.*\",pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=~\"$namespace\"}[3m]))",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "# Requests",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "round(sum(irate(istio_requests_total{destination_workload=\"$istio_service\"}[1m]))by(destination_workload_namespace), 0.001)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
     "options": {
      "content": "<h1 style=\"text-align: center; color:#3880eb; font-size: 35px\">Approval & Decline Stats</h1>\n"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 1, "x": 0, "y": 10 },
     "options": {
      "content": "<h1 style=\"text-align: center; color:#3880eb; font-size: 40px\">G</h1>\n<h1 style=\"text-align: center; color:#3880eb; font-size: 40px\">R</h1>\n<h1 style=\"text-align: center; color:#3880eb; font-size: 40px\">P</h1>\n<h1 style=\"text-align: center; color:#3880eb; font-size: 40px\">C</h1>\n"
     }
    },
    {
     "title": "Success Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 1, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((count(grpc_server_processing_duration_seconds_count{cluster=~\"$cluster\",container_name=~\"$container_name\",statusCode=~\"OK\"})) / (count(grpc_server_processing_duration_seconds_count{cluster=~\"$cluster\",container_name=~\"$container_name\"}))) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 3, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(grpc_server_processing_duration_seconds_count{cluster=~\"$cluster\",container_name=~\"$container_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 1, "x": 13, "y": 10 },
     "options": {
      "content": "<h1 style=\"text-align: center; color:#3880eb; font-size: 40px\">R</h1>\n<h1 style=\"text-align: center; color:#3880eb; font-size: 40px\">E</h1>\n<h1 style=\"text-align: center; color:#3880eb; font-size: 40px\">S</h1>\n<h1 style=\"text-align: center; color:#3880eb; font-size: 40px\">T</h1>\n"
     }
    },
    {
     "title": "Success Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 14, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((count(http_server_requests_seconds_count{cluster=~\"$cluster\",container_name=~\"$container_name\",method!~\"OPTIONS\",status=~\"2.*\"})) / (count(http_server_requests_seconds_count{cluster=~\"$cluster\",container_name=~\"$container_name\",method!~\"OPTIONS\"}))) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(http_server_requests_seconds_count{cluster=~\"$cluster\",container_name=~\"$container_name\",method!~\"OPTIONS\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "4xx Errors",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 3, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(grpc_server_processing_duration_seconds_count{cluster=~\"$cluster\",container_name=~\"$container_name\",statusCode=~\"NOT_FOUND\",statusCode=~\"PERMISSION_DENIED\",statusCode=~\"UNKNOWN\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "5xx Errors",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 7, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(grpc_server_processing_duration_seconds_count{cluster=~\"$cluster\",container_name=~\"$container_name\",statusCode=\"Internal\",statusCode=\"CANCELLED\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "400 Errors",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(http_server_requests_seconds_count{cluster=~\"$cluster\",container_name=~\"$container_name\",method!~\"OPTIONS\",status=~\"4.*\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "500 Errors",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(http_server_requests_seconds_count{cluster=~\"$cluster\",container_name=~\"$container_name\",method!~\"OPTIONS\",status=~\"5.*\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Integration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 14, "x": 4, "y": 2 },
     "options": {
      "content": "<h1 style=\"text-align: center; color:\t#FF9900; font-size: 35px\">DynamoDB metrics</h1>\n"
     }
    },
    {
     "title": "Time take for each call to DynamoDB for provided trackingNumber",
     "type": "table",
     "description": "Source: ElasticSearch; Index: landing_auth_events*\n\nInput: trackingNumber\n\nDescription: This panel will list down all the available calls to DynamoDB for a given trackingNumber and time taken for each one of them.",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 4 },
     "targets": [
      {
       "metrics": [
        {
         "id": "1",
         "settings": {
          "order": "desc",
          "size": "500",
          "useTimeRange": true
         },
         "type": "raw_document"
        }
       ],
       "query": "event.trackingNumber:\"$trackingNumber\"",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "title": "Time take for all call to DynamoDB",
     "type": "timeseries",
     "description": "Source: ElasticSearch; Index: landing_auth_events*\n\nMeasurements: _id:\"RMUAaYkBF2xGiC4SfA0U\"\n\nDescription: This panel will list down all the available calls to DynamoDB and time take for each of them over time, use this information to correlate the transactions you want to track for a specific trackingNumber. So to draw some analysis on what calls are expected.",
     "gridPos": { "h": 7, "w": 11, "x": 10, "y": 4 },
     "targets": [
      {
       "alias": "createClient",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.WebIdentityDynamoClientProviderImpl_WebIdentityDynamoClientProviderImpl.createDynamoClient.timeTaken",
         "id": "1",
         "meta": {
          "avg": true,
          "max": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "AssumeRole-createClient",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.AssumeRoleDynamoClientProviderImpl_AssumeRoleDynamoClientProviderImpl.createDynamoClient.timeTaken",
         "id": "1",
         "meta": {
          "avg": true,
          "max": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 14, "x": 4, "y": 11 },
     "options": {
      "content": "<h1 style=\"text-align: center; color:#f80000; font-size: 35px\">Oracle DB metrics</h1>\n"
     }
    },
    {
     "title": "Time for all available Interaction",
     "type": "stat",
     "gridPos": { "h": 6, "w": 18, "x": 3, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "bucketAggs": [
        {
         "field": "event.measurements.SqlPinProviderImpl_SqlPinProviderImpl.getProvider.slaType.keyword",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "event.measurements.SqlPinProviderImpl_SqlPinProviderImpl.getProvider.timeTaken",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "bucketAggs": [
        {
         "field": "event.measurements.SqlPinProviderImpl_SqlPinProviderImpl.getPinOffset.slaType.keyword",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "event.measurements.SqlPinProviderImpl_SqlPinProviderImpl.getPinOffset.timeTaken",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "bucketAggs": [
        {
         "field": "event.measurements.SqlPinProviderImpl_SqlPinProviderImpl.getPinOffset_Count.slaType.keyword",
         "id": "3",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "metrics": [
        {
         "field": "event.measurements.SqlPinProviderImpl_SqlPinProviderImpl.getPinOffset_Count.timeTaken",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "type": "text",
     "description": "Source: OpenSearch",
     "gridPos": { "h": 2, "w": 14, "x": 4, "y": 19 },
     "options": {
      "content": "<h1 style=\"text-align: center; color:#3880eb; font-size: 35px\">GRPC Service</h1>"
     },
     "targets": [
      { "accountId": "all", "queryMode": "Metrics", "region": "default", "statistic": "Average" }
     ]
    },
    {
     "title": "Gateway responseTimes",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 21 },
     "targets": [
      {
       "alias": "GetAuthGatewayConfigCache",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.PrimaryConfigCacheServiceImpl_PrimaryConfigCacheServiceImpl.getAuthgatewayConfigCache.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:\"9ddc8d81-7168-4d0a-903e-5e0dec9ae856\"",
       "timeField": "event.dateTime"
      },
      {
       "alias": "GatewayServiceImpl",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GatewayServiceImpl_GatewayServiceImpl.handleRequest.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:\"9ddc8d81-7168-4d0a-903e-5e0dec9ae856\"",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "title": "Time take for each call to Gateway service - $trackingNumber",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 21 },
     "targets": [
      {
       "alias": "/platform/gateway/message",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements./platform/gateway/message.timeTaken",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "GatewayServiceImpl_handleRequest_Count",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GatewayServiceImpl_GatewayServiceImpl.handleRequest_Count.timeTaken",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "GatewayServiceImpl_handleRequest",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GatewayServiceImpl_GatewayServiceImpl.handleRequest.timeTaken",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getAuthGatewayConfigCache",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.PrimaryConfigCacheServiceImpl_PrimaryConfigCacheServiceImpl.getAuthgatewayConfigCache.timeTaken",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "GatewayServiceImpl.handleRequest_Count",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.PrimaryConfigCacheServiceImpl_PrimaryConfigCacheServiceImpl.getAuthgatewayConfigCache_Count.timeTaken",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "type": "text",
     "description": "Source: OpenSearch",
     "gridPos": { "h": 2, "w": 14, "x": 4, "y": 28 },
     "options": {
      "content": "<h1 style=\"text-align: center; color:#3880eb; font-size: 35px\">Tokenization Service</h1>"
     },
     "targets": [
      { "accountId": "all", "queryMode": "Metrics", "region": "default", "statistic": "Average" }
     ]
    },
    {
     "title": "Tokenization calls responseTimes",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 30 },
     "targets": [
      {
       "alias": "deTokenize",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GrpcDataTokenizationServiceImpl_GrpcDataTokenizationServiceImpl.deTokenize.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "tokenizationGRPC",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.com.example.enterprise.tokenization.tokenizationgrpc.service.TokenizationService_com.example.enterprise.tokenization.tokenizationgrpc.service.TokenizationService.getMultiClearValue.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "tokenize",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GrpcDataTokenizationServiceImpl_GrpcDataTokenizationServiceImpl.tokenize.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getMultiToken",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.TokenizationGrpcService.Tokenization/getMultiToken.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getMultiClearValue",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.TokenizationGrpcService.Tokenization/getMultiClearValue.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getNamespaceForPortfolioId",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.TokenizationGrpcService.Tokenization/getNamespaceForPortfolioId.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "title": "Tokenization calls responseTimes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 30 },
     "targets": [
      {
       "alias": "deTokenize",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GrpcDataTokenizationServiceImpl_GrpcDataTokenizationServiceImpl.deTokenize.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "tokenizationGRPC",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.com.example.enterprise.tokenization.tokenizationgrpc.service.TokenizationService_com.example.enterprise.tokenization.tokenizationgrpc.service.TokenizationService.getMultiClearValue.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "tokenize",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GrpcDataTokenizationServiceImpl_GrpcDataTokenizationServiceImpl.tokenize.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getMultiToken",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.TokenizationGrpcService.Tokenization/getMultiToken.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getMultiClearValue",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.TokenizationGrpcService.Tokenization/getMultiClearValue.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getNamespaceForPortfolioId",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.TokenizationGrpcService.Tokenization/getNamespaceForPortfolioId.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      }
     ]
    }
   ]
  },
  { "title": "NFR Execution Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "    ",
   "type": "text",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 3 },
   "options": {
    "content": "\nPlease refer to: [NFR Test Framework Results](https://grafana-iss-devto.tooling.dev.example.aws/d/dF7TKi94k/nfr-test-framework-execution-dashboard?orgId=1)"
   }
  },
  { "title": "NFR Evaluation Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "  ",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 6 },
   "options": {
    "content": "Please refer to: [NFR Evaluation Results](https://grafana-iss-devto.tooling.dev.example.aws/d/pUk0XkzSk/nfr-evaluation-results)"
   }
  },
  {
   "title": "K8s Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "# of Pods / # of Restarts",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_info{pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=~\"$namespace\"})",
       "legendFormat": "  # Pods"
      },
      {
       "expr": "count(count(container_memory_usage_bytes{pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=\"$namespace\"}) by (kubernetes_io_hostname))",
       "legendFormat": "# Nodes"
      },
      {
       "expr": "sum(changes(kube_pod_container_status_restarts_total{namespace=~\"$namespace\",pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"}[15m]))",
       "legendFormat": " # Restarts"
      }
     ]
    },
    {
     "title": "CPU Usage/ limit / Request",
     "type": "bargauge",
     "description": "Datasource: Thanos\n\nInput: namespace, pod\n\nDescription: Increase in CPU will show direct impact on application availability. Check if the app capacity is in right scale. If there is no HPA setup, make sure if the deployment is properly scaled.",
     "gridPos": { "h": 5, "w": 7, "x": 5, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "cores" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(rate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\" ,namespace=~\"^$namespace$\",pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"}[3m]))",
       "legendFormat": "CPU Usage - Average per Pod"
      },
      {
       "expr": "max(kube_pod_container_resource_requests_cpu_cores{namespace=~\"^$namespace$\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"}) ",
       "legendFormat": " Request"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_cpu_cores{namespace=~\"^$namespace$\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory Usage/ limit / Request",
     "type": "bargauge",
     "description": "Datasource: Thanos\n\nInput: namespace, pod\n\nDescription: Increase in Memory will show direct impact on application availability. Check if the app is allocated with enough resources. If there is no HPA setup, make sure if the deployment is properly scaled.",
     "gridPos": { "h": 5, "w": 7, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg(sum(container_memory_usage_bytes{container!=\"\", container!=\"POD\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=\"$namespace\"}) by (id,pod) - sum(container_memory_cache{container!=\"\", container!=\"POD\", pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=\"$namespace\"}) by (id,pod))",
       "legendFormat": "Memory Usage - Average Per Pod"
      },
      {
       "expr": "max(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod_name=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"}) ",
       "legendFormat": " Request"
      },
      {
       "expr": "max(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod_name=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\"})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Total Network Pressure",
     "type": "stat",
     "description": "Datasource: Thanos\n\nThresholds: Green: < 500 MBps; Yellow: > 500 MBps; Red: > 1000 MBps\n\nInput: pod, namespace\n\nDescription: Drop in ether In or Out indicated the app is in healthy, check if the app is able to communicate to subsequent services.",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{name=~\"^k8s_.*\",pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=~\"$namespace\"}[3m]))",
       "legendFormat": "In"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{name=~\"^k8s_.*\",pod=~\"$deployment-(([a-z0-9]*)|([a-z0-9]*-[a-z0-9]*)|[0-9])\", namespace=~\"$namespace\"}[3m]))",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  }
 ]
}