{
 "title": "Service Interaction",
 "time": { "from": "2023-07-01T04:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "apiType",
    "query": "{\"find\": \"terms\", \"field\": \"event.type.keyword\"}"
   },
   { "name": "trackingNumber" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "timeTaken to all calls for $trackingNumber",
     "type": "table",
     "description": "Source: ElasticSearch; Index: landing_auth_events*\n\nInput: trackingNumber\n\nDescription: When monitoring a service interaction it's important to understand the list of every interaction b/w services and time taken for each one of them. This panel highlights the calls that's taking more time, violating the thresholds.\n\nGreen: [0 - 100]\t\t\t\nYellow: [101 - 150]\t\t\t\nRed: [151 - 10000]\n",
     "gridPos": { "h": 12, "w": 14, "x": 0, "y": 25 },
     "targets": [
      {
       "metrics": [
        {
         "id": "1",
         "settings": {
          "order": "desc",
          "size": "500",
          "useTimeRange": true
         },
         "type": "raw_document"
        }
       ],
       "query": "event.trackingNumber:\"$trackingNumber\"",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "title": "Calls to application based for $trackingNumber",
     "type": "table",
     "gridPos": { "h": 4, "w": 7, "x": 14, "y": 25 },
     "targets": [
      {
       "alias": "Web createClient",
       "bucketAggs": [
        {
         "field": "event.application.keyword",
         "id": "9",
         "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
         "type": "terms"
        }
       ],
       "luceneQueryType": "Metric",
       "metrics": [
        { "id": "6", "type": "count" }
       ],
       "query": "event.trackingNumber:\"$trackingNumber\"",
       "timeField": "event.dateTime"
      }
     ]
    }
   ]
  },
  {
   "title": "Interaction with DynamoDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total TimeTaken for all Dynamo Interactions",
     "type": "stat",
     "description": "Source: ElasticSearch; Index: landing_auth_events*\n\nInput: trackingNumber\n\nDescription: This panel show the total time taken for all the interactions to DynamoDB",
     "gridPos": { "h": 4, "w": 7, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "WebCreateClient",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "4", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.WebIdentityDynamoClientProviderImpl_WebIdentityDynamoClientProviderImpl.createDynamoClient.timeTaken",
         "hide": false,
         "id": "1",
         "meta": {
          "avg": false,
          "count": true,
          "max": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:$trackingNumber",
       "timeField": "event.dateTime"
      },
      {
       "alias": "fetchAccountDetails",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "4", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.AccountServiceDynamoProviderImpl_AccountServiceDynamoProviderImpl.fetchAccountDetails.timeTaken",
         "hide": false,
         "id": "1",
         "meta": {
          "count": true,
          "max": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:$trackingNumber",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "title": "List of available calls to Dynamo",
     "type": "table",
     "description": "Source: ElasticSearch; Index: landing_auth_events*\n\nMeasurements: _id:\"RMUAaYkBF2xGiC4SfA0U\"\n\nDescription: This panel will list down all the available calls to DynamoDB, use this information to correlate the transactions you want to track for a specific trackingNumber. So to draw some analysis on what calls are expected.",
     "gridPos": { "h": 4, "w": 10, "x": 7, "y": 18 },
     "targets": [
      {
       "metrics": [
        {
         "id": "1",
         "settings": {
          "order": "desc",
          "size": "500",
          "useTimeRange": true
         },
         "type": "raw_document"
        }
       ],
       "query": "_id:\"RMUAaYkBF2xGiC4SfA0U\"",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "title": "Time take for each call to DynamoDB for provided trackingNumber",
     "type": "table",
     "description": "Source: ElasticSearch; Index: landing_auth_events*\n\nInput: trackingNumber\n\nDescription: This panel will list down all the available calls to DynamoDB for a given trackingNumber and time taken for each one of them.",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 22 },
     "targets": [
      {
       "metrics": [
        {
         "id": "1",
         "settings": {
          "order": "desc",
          "size": "500",
          "useTimeRange": true
         },
         "type": "raw_document"
        }
       ],
       "query": "event.trackingNumber:\"$trackingNumber\"",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "title": "Time take for all call to DynamoDB",
     "type": "timeseries",
     "description": "Source: ElasticSearch; Index: landing_auth_events*\n\nMeasurements: _id:\"RMUAaYkBF2xGiC4SfA0U\"\n\nDescription: This panel will list down all the available calls to DynamoDB and time take for each of them over time, use this information to correlate the transactions you want to track for a specific trackingNumber. So to draw some analysis on what calls are expected.",
     "gridPos": { "h": 7, "w": 11, "x": 10, "y": 22 },
     "targets": [
      {
       "alias": "createClient",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.WebIdentityDynamoClientProviderImpl_WebIdentityDynamoClientProviderImpl.createDynamoClient.timeTaken",
         "id": "1",
         "meta": {
          "avg": true,
          "max": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "AssumeRole-createClient",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.AssumeRoleDynamoClientProviderImpl_AssumeRoleDynamoClientProviderImpl.createDynamoClient.timeTaken",
         "id": "1",
         "meta": {
          "avg": true,
          "max": false,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      }
     ]
    }
   ]
  },
  { "title": "Interaction with OracleDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Time for all available Interaction",
   "type": "stat",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "event.measurements.SqlPinProviderImpl_SqlPinProviderImpl.getProvider.slaType.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "event.measurements.SqlPinProviderImpl_SqlPinProviderImpl.getProvider.timeTaken",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "event.trackingNumber:*",
     "timeField": "event.dateTime"
    },
    {
     "bucketAggs": [
      {
       "field": "event.measurements.SqlPinProviderImpl_SqlPinProviderImpl.getPinOffset.slaType.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "event.measurements.SqlPinProviderImpl_SqlPinProviderImpl.getPinOffset.timeTaken",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "event.trackingNumber:*",
     "timeField": "event.dateTime"
    },
    {
     "bucketAggs": [
      {
       "field": "event.measurements.SqlPinProviderImpl_SqlPinProviderImpl.getPinOffset_Count.slaType.keyword",
       "id": "3",
       "settings": { "min_doc_count": "0", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "event.measurements.SqlPinProviderImpl_SqlPinProviderImpl.getPinOffset_Count.timeTaken",
       "id": "1",
       "type": "avg"
      }
     ],
     "query": "event.trackingNumber:*",
     "timeField": "event.dateTime"
    }
   ]
  },
  {
   "title": "Interaction with other microservices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "description": "Source: OpenSearch",
     "gridPos": { "h": 2, "w": 16, "x": 3, "y": 19 },
     "options": {
      "content": "<h1 style=\"text-align: center; color:#3880eb; font-size: 35px\">GRPC Service</h1>"
     },
     "targets": [
      { "accountId": "all", "queryMode": "Metrics", "region": "default", "statistic": "Average" }
     ]
    },
    {
     "title": "List of calls to Gateway service",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 21 },
     "targets": [
      {
       "metrics": [
        {
         "id": "1",
         "settings": {
          "order": "desc",
          "size": "500",
          "useTimeRange": true
         },
         "type": "raw_document"
        }
       ],
       "query": "_id:\"RMUAaYkBF2xGiC4SfA0U\"",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "title": "Time take for each call to Gateway service for selected trackingNumber",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 10, "y": 21 },
     "targets": [
      {
       "metrics": [
        {
         "id": "1",
         "settings": {
          "order": "desc",
          "size": "500",
          "useTimeRange": true
         },
         "type": "raw_document"
        }
       ],
       "query": "event.trackingNumber:\"$trackingNumber\"",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "title": "Gateway responseTimes",
     "type": "barchart",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 28 },
     "targets": [
      {
       "alias": "GetAuthGatewayConfigCache",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.PrimaryConfigCacheServiceImpl_PrimaryConfigCacheServiceImpl.getAuthgatewayConfigCache.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:\"9ddc8d81-7168-4d0a-903e-5e0dec9ae856\"",
       "timeField": "event.dateTime"
      },
      {
       "alias": "GatewayServiceImpl",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GatewayServiceImpl_GatewayServiceImpl.handleRequest.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:\"9ddc8d81-7168-4d0a-903e-5e0dec9ae856\"",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "title": "Time take for each call to Gateway service - $trackingNumber",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 17, "x": 7, "y": 28 },
     "targets": [
      {
       "alias": "/platform/gateway/message",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto", "min_doc_count": "0", "trimEdges": "0" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements./platform/gateway/message.timeTaken",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "GatewayServiceImpl_handleRequest_Count",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GatewayServiceImpl_GatewayServiceImpl.handleRequest_Count.timeTaken",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "GatewayServiceImpl_handleRequest",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GatewayServiceImpl_GatewayServiceImpl.handleRequest.timeTaken",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getAuthGatewayConfigCache",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.PrimaryConfigCacheServiceImpl_PrimaryConfigCacheServiceImpl.getAuthgatewayConfigCache.timeTaken",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "GatewayServiceImpl.handleRequest_Count",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.PrimaryConfigCacheServiceImpl_PrimaryConfigCacheServiceImpl.getAuthgatewayConfigCache_Count.timeTaken",
         "id": "1",
         "type": "avg"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "type": "text",
     "description": "Source: OpenSearch",
     "gridPos": { "h": 2, "w": 15, "x": 3, "y": 35 },
     "options": {
      "content": "<h1 style=\"text-align: center; color:#3880eb; font-size: 35px\">Tokenization Service</h1>"
     },
     "targets": [
      { "accountId": "all", "queryMode": "Metrics", "region": "default", "statistic": "Average" }
     ]
    },
    {
     "title": "List of calls to Tokenization service",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
     "targets": [
      {
       "metrics": [
        {
         "id": "1",
         "settings": {
          "order": "desc",
          "size": "500",
          "useTimeRange": true
         },
         "type": "raw_document"
        }
       ],
       "query": "_id:\"RMUAaYkBF2xGiC4SfA0U\"",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "title": "List of calls to Tokenization service for $trackingNumber",
     "type": "table",
     "gridPos": { "h": 5, "w": 10, "x": 8, "y": 37 },
     "targets": [
      {
       "metrics": [
        {
         "id": "1",
         "settings": {
          "order": "desc",
          "size": "500",
          "useTimeRange": true
         },
         "type": "raw_document"
        }
       ],
       "query": "event.trackingNumber:\"$trackingNumber\"",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "title": "Tokenization calls responseTimes",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 42 },
     "targets": [
      {
       "alias": "deTokenize",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GrpcDataTokenizationServiceImpl_GrpcDataTokenizationServiceImpl.deTokenize.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "tokenizationGRPC",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.com.example.enterprise.tokenization.tokenizationgrpc.service.TokenizationService_com.example.enterprise.tokenization.tokenizationgrpc.service.TokenizationService.getMultiClearValue.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "tokenize",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GrpcDataTokenizationServiceImpl_GrpcDataTokenizationServiceImpl.tokenize.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getMultiToken",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.TokenizationGrpcService.Tokenization/getMultiToken.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getMultiClearValue",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.TokenizationGrpcService.Tokenization/getMultiClearValue.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getNamespaceForPortfolioId",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.TokenizationGrpcService.Tokenization/getNamespaceForPortfolioId.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      }
     ]
    },
    {
     "title": "Tokenization calls responseTimes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 42 },
     "targets": [
      {
       "alias": "deTokenize",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GrpcDataTokenizationServiceImpl_GrpcDataTokenizationServiceImpl.deTokenize.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "tokenizationGRPC",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.com.example.enterprise.tokenization.tokenizationgrpc.service.TokenizationService_com.example.enterprise.tokenization.tokenizationgrpc.service.TokenizationService.getMultiClearValue.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "tokenize",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.GrpcDataTokenizationServiceImpl_GrpcDataTokenizationServiceImpl.tokenize.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getMultiToken",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.TokenizationGrpcService.Tokenization/getMultiToken.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getMultiClearValue",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.TokenizationGrpcService.Tokenization/getMultiClearValue.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      },
      {
       "alias": "getNamespaceForPortfolioId",
       "bucketAggs": [
        { "field": "event.dateTime", "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "field": "event.measurements.TokenizationGrpcService.Tokenization/getNamespaceForPortfolioId.timeTaken",
         "id": "1",
         "meta": {
          "avg": false,
          "max": true,
          "std_deviation_bounds_lower": false,
          "std_deviation_bounds_upper": false
         },
         "type": "extended_stats"
        }
       ],
       "query": "event.trackingNumber:*",
       "timeField": "event.dateTime"
      }
     ]
    }
   ]
  }
 ]
}