{
 "title": "Grafana-Operator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "awsaccount",
    "query": {
     "query": "label_values(controller_runtime_active_workers,awsaccount)"
    }
   },
   {
    "name": "region",
    "query": {
     "query": "label_values(controller_runtime_active_workers,region)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(controller_runtime_active_workers,cluster)"
    }
   },
   {
    "name": "controller",
    "query": {
     "query": "label_values(controller_runtime_active_workers,controller)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Controller Runtime Reconciliation Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(controller_runtime_reconcile_time_seconds_bucket{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", controller=~\"$controller\"}[5m])))",
     "legendFormat": ".50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(controller_runtime_reconcile_time_seconds_bucket{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", controller=~\"$controller\"}[5m])))",
     "legendFormat": ".90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(controller_runtime_reconcile_time_seconds_bucket{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", controller=~\"$controller\"}[5m])))",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Reconciliation error count by controller",
   "type": "timeseries",
   "description": "Per-second rate of reconciliation errors as measured over the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_errors_total{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", controller=~\"$controller\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seconds of P50/90/99 Items Stay in Work Queue",
   "type": "graph",
   "description": "Total time for NGINX and upstream servers to process a request and send a response",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(workqueue_queue_duration_seconds_bucket{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", name=~\"$controller\"}[5m])))",
     "legendFormat": ".50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(workqueue_queue_duration_seconds_bucket{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", name=~\"$controller\"}[5m])))",
     "legendFormat": ".90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(workqueue_queue_duration_seconds_bucket{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", name=~\"$controller\"}[5m])))",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Seconds of P50/90/99 Items Processed in Work Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(workqueue_work_duration_seconds_bucket{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", name=~\"$controller\"}[5m])))",
     "legendFormat": ".50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(workqueue_work_duration_seconds_bucket{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", name=~\"$controller\"}[5m])))",
     "legendFormat": ".90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(workqueue_work_duration_seconds_bucket{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", name=~\"$controller\"}[5m])))",
     "legendFormat": ".99"
    }
   ]
  },
  {
   "title": "Certificate Read Error Count ",
   "type": "timeseries",
   "description": "Per-second rate of reconciliation errors as measured over the last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(certwatcher_read_certificate_errors_total{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", controller=~\"$controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Add Rate in Work Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(instance, name) (rate(workqueue_adds_total{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", name=~\"$controller\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retry Rate in Work Queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by(instance, name) (rate(workqueue_retries_total{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", name=~\"$controller\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{container=\"grafana-operator\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}