{
 "title": "Pushgateway Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pushgateway HTTP Push Duration Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(pushgateway_http_push_duration_seconds)"
    },
    {},
    {}
   ]
  },
  {
   "title": "CPU and Memory Usage for Pushgateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{container=\"pushgateway\"}"
    },
    {
     "expr": "container_memory_usage_bytes{container=\"pushgateway\"}"
    }
   ]
  },
  {
   "title": "Total Requests per handler",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pushgateway_http_requests_total) by (handler)"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(pushgateway_http_requests_total[5m]))"
    }
   ]
  }
 ]
}