{
 "title": "External-dns",
 "description": "Grafana dashboard to display external-dns metrics",
 "tags": [
  "external-dns",
  "dns"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_THANOS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "awsaccount",
    "label": "awsaccount",
    "query": {
     "query": "label_values(external_dns_controller_last_sync_timestamp_seconds,awsaccount)"
    }
   },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(external_dns_controller_last_sync_timestamp_seconds,region)"
    }
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(external_dns_controller_last_sync_timestamp_seconds,cluster)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{awsaccount=\"$awsaccount\", region=\"$region\", cluster=\"$cluster\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "External-dns endpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total external-dns registry endpoints",
   "type": "timeseries",
   "description": "Number of Endpoints in the registry",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(external_dns_registry_endpoints_total{awsaccount=\"$awsaccount\",region=\"$region\", cluster=\"$cluster\",container=\"external-dns\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total external-dns source endpoints",
   "type": "timeseries",
   "description": "Number of Endpoints in all sources",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "external_dns_source_endpoints_total{awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\",container=\"external-dns\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "External-dns errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total external-dns registry errors",
   "type": "timeseries",
   "description": "Number of Registry errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "external_dns_registry_errors_total {awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\",container=\"external-dns\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total external-dns source errors",
   "type": "timeseries",
   "description": "Number of Source errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "external_dns_source_errors_total { awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\",container=\"external-dns\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Timestamp of last successful sync with the DNS provider",
   "type": "timeseries",
   "description": "Timestamp of last successful sync with the DNS provider",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    {
     "expr": "1000 * (external_dns_controller_last_sync_timestamp_seconds{awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\",container=\"external-dns\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "External-Dns Generic Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{container=\"external-dns\", status!=\"200\", region=\"$region\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External-dns sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\",container=\"external-dns\"}[30m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"external-dns\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", container=\"external-dns\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", type=\"hard\",resource=\"requests.memory\",container=\"external-dns\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{ awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\",type=\"hard\",resource=\"limits.memory\",container=\"external-dns\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "External-dns pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{image!=\"\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\",container=~\"external-dns\"})"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{ awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\",resource=\"memory\", container=\"external-dns\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{ awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", image!=\"\", container=\"external-dns\"}) by (pod) / sum(kube_pod_container_resource_requests{awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\",resource=\"memory\",container=\"external-dns\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{pod=~\"$pod\", container=\"external-dns\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\", container=\"external-dns\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{pod=~\"$pod\", container=\"external-dns\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\",resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{pod=~\"$pod\", container=\"external-dns\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{pod=~\"$pod\", container=\"external-dns\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{pod=~\"$pod\", container=\"external-dns\", awsaccount=~\"$awsaccount\", region=~\"$region\", cluster=~\"$cluster\",}) by (pod)"
    }
   ]
  }
 ]
}