{
 "title": "Istio Wasm Extension Dashboard",
 "description": "Istio Wasm Extension Dashboard version 1.15.0-beta.0",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_THANOS", "label": "DataSource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Wasm VMs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_wasm_envoy_wasm_runtime_null_active{cluster=\"$cluster\"})",
     "legendFormat": "native"
    },
    {
     "expr": "avg(envoy_wasm_envoy_wasm_runtime_v8_active{cluster=\"$cluster\"})",
     "legendFormat": "v8"
    }
   ]
  },
  {
   "title": "Created",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_wasm_envoy_wasm_runtime_null_created{cluster=\"$cluster\"})",
     "legendFormat": "native"
    },
    {
     "expr": "avg(envoy_wasm_envoy_wasm_runtime_v8_created{cluster=\"$cluster\"})",
     "legendFormat": "v8"
    }
   ]
  },
  {
   "title": "Wasm Module Remote Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cache Entry",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_wasm_remote_load_cache_entries{cluster=\"$cluster\"})",
     "legendFormat": "entries"
    }
   ]
  },
  {
   "title": "Cache Visit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_wasm_remote_load_cache_hits{cluster=\"$cluster\"})",
     "legendFormat": "hits"
    },
    {
     "expr": "avg(envoy_wasm_remote_load_cache_misses{cluster=\"$cluster\"})",
     "legendFormat": "misses"
    },
    {
     "expr": "avg(envoy_wasm_remote_load_cache_negative_hits{cluster=\"$cluster\"})",
     "legendFormat": "negative hits"
    }
   ]
  },
  {
   "title": "Remote Fetch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(envoy_wasm_remote_load_fetch_failures{cluster=\"$cluster\"})",
     "legendFormat": "failures"
    },
    {
     "expr": "avg(envoy_wasm_remote_load_fetch_successes{cluster=\"$cluster\"})",
     "legendFormat": "successes"
    }
   ]
  },
  {
   "title": "Proxy Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{container=\"istio-proxy\",cluster=\"$cluster\"})",
     "legendFormat": "Total (k8s)"
    }
   ]
  },
  {
   "title": "vCPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"istio-proxy\",cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Total (k8s)"
    }
   ]
  }
 ]
}