{
 "title": "Kubernetes Control Plane Components",
 "description": "Dashboard for Kubernetes Control Plane Components",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_THANOS", "label": "DataSource", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "resolution",
    "query": "1m, 3m, 5m, 10m, 15m, 20m, 25m, 30m"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Autoscaler New", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Autoscaler Replicas status",
   "type": "stat",
   "description": "Cluster Autoscaler Stats",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "repeat": "cluster",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "kube_deployment_status_replicas_available{cluster=\"$cluster\", deployment=~\".*autoscaler.*\"} / kube_deployment_spec_replicas{cluster=\"$cluster\", deployment=~\".*autoscaler.*\"}",
     "legendFormat": "__auto",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Cluster Autoscaler Pod Count",
   "type": "stat",
   "description": "Cluster Autoscaler",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "repeat": "cluster",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "kube_deployment_status_replicas_available{cluster=\"$cluster\", deployment=~\".*autoscaler.*\"}",
     "legendFormat": "__auto",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Cluster Autoscaler Pod Status New",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 5, "y": 13 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{cluster=\"$cluster\", phase=~\".*Running.*|.*Failed.*|.*Pending.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "sidecar injector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "sidecarinjector Replicas status",
   "type": "stat",
   "description": "sidecarinjector Stats",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "repeat": "cluster",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "kube_deployment_status_replicas_available{cluster=\"$cluster\", deployment=~\".*sidecarinjector.*\"} / kube_deployment_spec_replicas{cluster=\"$cluster\", deployment=~\".*sidecarinjector.*\"}",
     "legendFormat": "__auto",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "sidecarinjector Pod Count",
   "type": "stat",
   "description": "sidecarinjector stats",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
   "repeat": "cluster",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "kube_deployment_status_replicas_available{cluster=\"$cluster\", deployment=~\".*sidecarinjector.*\"}",
     "legendFormat": "__auto",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "sidecar injector pod status",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 5, "y": 31 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{cluster=\"$cluster\", phase=~\".*Running.*|.*Failed.*|.*Pending.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sidecar injector pod count new",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{cluster=\"$cluster\", deployment=~\".*sidecarinjector.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sidecar injector",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{cluster=\"$cluster\", container=~\".*sidecarinjector.*\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "nginx", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "nginx",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{cluster=\"$cluster\", pod=~\".*nginx.*\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nginx pod status",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 42 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{cluster=\"$cluster\", pod=~\"sc-nginx.*\", phase=~\".*Running.*|.*Failed.*|.*Pending.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Istio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "istio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{cluster=\"$cluster\", pod=~\".*istio.*\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Istio pod status",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 48 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{cluster=\"$cluster\", pod=~\".*istio.*\", phase=~\".*Running.*|.*Failed.*|.*Pending.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "satprom Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "satprom",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{cluster=\"$cluster\", pod=~\".*satprom.*\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "satprom pod status",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 54 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{cluster=\"$cluster\", pod=~\".*satprom.*\", phase=~\".*Running.*|.*Failed.*|.*Pending.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "fluent-bit details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "fluent-bit",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{cluster=\"$cluster\", container=~\".*fluent-bit.*\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fluent-bit pod status",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 60 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{cluster=\"$cluster\", pod=~\".*fluent-bit.*\", phase=~\".*Running.*|.*Failed.*|.*Pending.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Autoscaler Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "Cluster Autoscaler",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{cluster=\"$cluster\", container=~\".*cluster-autoscaler.*\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Autoscaler Pod Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{cluster=\"$cluster\", pod=~\".*cluster-autoscaler.*\", phase=~\".*Running.*|.*Failed.*|.*Pending.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "External DNS Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "External DNS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{cluster=\"$cluster\", container=~\".*external-dns.*\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External DNS Pod Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 72 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{cluster=\"$cluster\", pod=~\".*external-dns.*\", phase=~\".*Running.*|.*Failed.*|.*Pending.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}