{
 "title": "Kubernetes Calico",
 "description": "Calico cluster monitoring dashboard",
 "tags": [ "calico" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_THANOS", "label": "DataSource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "label_values(cluster)" } }
  ]
 },
 "panels": [
  {
   "title": "Felix",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Local Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_active_local_endpoints{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  },
  {
   "title": "Active Local Policies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_active_local_policies{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  },
  {
   "title": "Active Local Selectors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_active_local_selectors{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  },
  {
   "title": "Active Local Tags",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_active_local_tags{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Host Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_cluster_num_host_endpoints{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  },
  {
   "title": "Cluster Workload Endpoints",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_cluster_num_workload_endpoints{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  },
  {
   "title": "Clusters Hosts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_cluster_num_hosts{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  },
  {
   "title": "Active IP Sets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_ipsets_calico{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  },
  {
   "title": "Active IP Tables Chains",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_iptables_chains{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  },
  {
   "title": "IP Set Command Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_ipset_errors{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  },
  {
   "title": "IP Tables Save Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_iptables_save_errors{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  },
  {
   "title": "IP Tables Restore Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_iptables_restore_errors{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  },
  {
   "title": "Felix Resyncing Datastore",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_resyncs_started{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  },
  {
   "title": "Dataplane failed updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "felix_int_dataplane_failures{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }} {{ cluster }}"
    }
   ]
  }
 ]
}