{
 "title": "Node - k8s-monitor",
 "description": "Dashboard develop to work together with k8s-monitor to visualize Node-Exporter metrics.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_THANOS", "label": "DataSource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{job=\"node-exporter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Number of CPU in the cluster",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{cpu=\"0\"}) by (cpu) / 2"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Number of Memory in the cluster",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Nodes in cluster",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance)(node_boot_time_seconds))"
    }
   ]
  },
  {
   "title": "Nodes in cluster (History)",
   "type": "graph",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(count by (instance)(node_boot_time_seconds))"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Number of CPU in the cluster",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "description": "Number of Memory in the cluster",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU/Mem Percentage",
   "type": "graph",
   "description": "CPU and Memory usage percentage",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg((sum by (instance) (rate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$node\"}[5m]))) / count(count (node_cpu_seconds_total{instance=~\"$node\"}) by (instance,cpu)) by (instance))",
     "legendFormat": "CPU"
    },
    {
     "expr": "avg(((node_memory_MemTotal_bytes{instance=~\"$node\"}) - (node_memory_MemFree_bytes{instance=~\"$node\"} + node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"})) / (node_memory_MemTotal_bytes{instance=~\"$node\"}))",
     "legendFormat": "MEM"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Percentage (AVG All selected nodes)",
   "type": "gauge",
   "description": "CPU usage percentage average all selected nodes",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((sum by (instance) (rate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$node\"}[5m]))) / count(count (node_cpu_seconds_total{instance=~\"$node\"}) by (instance,cpu)) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Percentage",
   "type": "graph",
   "description": "CPU usage percentage",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (instance) (rate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$node\"}[5m]))) / count(count (node_cpu_seconds_total{instance=~\"$node\"}) by (instance,cpu)) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Number of CPU in node",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Usage (Milicores)",
   "type": "graph",
   "description": "CPU usage by Milicores",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (sum by (cpu,instance) (rate(node_cpu_seconds_total{mode!=\"idle\",instance=~\"$node\"}[5m]))) * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU IDLE Percentage (AVG All selected nodes)",
   "type": "gauge",
   "description": "CPU IDLE usage percentage average all selected nodes",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((sum by (instance) (rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node\"}[5m]))) / count(count (node_cpu_seconds_total{instance=~\"$node\"}) by (instance,cpu)) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU IDLE (Milicores)",
   "type": "graph",
   "description": "CPU IDLE by Milicores",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (sum by (cpu,instance) (rate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node\"}[5m]))) * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Percentage (AVG All selected nodes)",
   "type": "gauge",
   "description": "Memory usage percentage average all selected nodes",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(((node_memory_MemTotal_bytes{instance=~\"$node\"}) - (node_memory_MemFree_bytes{instance=~\"$node\"} + node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"})) / (node_memory_MemTotal_bytes{instance=~\"$node\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Percentage",
   "type": "graph",
   "description": "Memory usage percentage",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 37 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$node\"}) - (node_memory_MemFree_bytes{instance=~\"$node\"} + node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"})) / (node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Total (Sum by nodes selected)",
   "type": "stat",
   "description": "Memory total per node selected",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$node\"}) - (node_memory_MemFree_bytes{instance=~\"$node\"} + node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory free",
   "type": "graph",
   "description": "Memory that can be allocated by process",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\"} + node_memory_Cached_bytes{instance=~\"$node\"} + node_memory_Buffers_bytes{instance=~\"$node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk written (Bytes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_disk_written_bytes_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Disk written (Seconds)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_disk_write_time_seconds_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Disk read (Bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_disk_read_bytes_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Disk written (Seconds)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_disk_read_time_seconds_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Disk I/O (Seconds)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_disk_io_time_seconds_total{instance=~\"$node\"}[5m]))",
     "legendFormat": "{{instance}} "
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network receive (Bytes)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(node_network_receive_bytes_total{instance=~\"$node\"}[5m]))",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Network transmite (Bytes)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(node_network_transmit_bytes_total{instance=~\"$node\"}[5m]))",
       "legendFormat": "{{instance}} "
      }
     ]
    },
    {
     "title": "Network receive/transmit error (Bytes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_network_transmit_errs_total{instance=~\"$node\"}[5m])",
       "legendFormat": "{{instance}} / R"
      },
      {
       "expr": "rate(node_network_receive_errs_total{instance=~\"$node\"}[5m])",
       "legendFormat": "{{instance}} / T"
      }
     ]
    }
   ]
  }
 ]
}